- name: Demo on tasks
  hosts: all                        # hosts group name
  gather_facts: no                 # disable gathering facts, it is enabled by default, it will collect system information like OS, CPU, Memory, etc. which is not required in this playbook.
  tasks:
    - name: Installing frontend
      ansible.builtin.debug:
        msg: Installing frontend
      tags: frontend

    - name: Starting frontend
      ansible.builtin.debug:
        msg: Starting frontend
      tags: frontend

    - name: Installing DB
      ansible.builtin.debug:
        msg: Installing DB
      tags: DB

    - name: Starting DB
      ansible.builtin.debug:
        msg: Starting DB                
      tags: DB


    - name: Installing Backend
      ansible.builtin.debug:
        msg: Installing Backend
      tags: Backend

    - name: Starting Backend
      ansible.builtin.debug:
        msg: Starting Backend  
      tags: Backend      

  # Command : 
  # $ ansible-playbook -i inv -e ansible_user=ec2-user -e ansible_password=your_password 007-tags.yaml -t "Backend"
  
  # $ ansible-playbook -i inv -e ansible_user=ec2-user -e ansible_password=your_password 007-tags.yaml --tags "DB"
  # $ ansible-playbook -i inv -e ansible_user=ec2-user -e ansible_password=your_password 007-tags.yaml --tags "frontend"
  # $ ansible-playbook -i inv -e ansible_user=ec2-user -e ansible_password=your_password 007-tags.yaml --tags "Backend"

  