- name: Configuring hostname
  ansible.builtin.shell: set-hostname "{{COMPONENT}}-{{ENV}}"

- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present


- name: Copy file with owner and permissions
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/default.d/nginx.conf

- name: App Pre-requisite Tasks
  ansible.builtin.include_role:           # through this we can call any role inside another role
    name: common                          # Name of the role to be called
    tasks_from: pre-req.yml               # Name of the file to be called inside the role



- name: Restarting nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
