- name: Configuring hostname
  ansible.builtin.shell: set-hostname {{ COMPONENT }}

- name: Install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Starting mysqld service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true

- name: Create a directory
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1




